const DB_NAME='slopskip-public-v1',STORE='tracks',$=selector=>document.querySelector(selector);
let tracks=[],visible=[],current=null,audioUrl=null,nowArtUrl=null,artUrls=[],editing=null,pendingArt=null,lastPlaybackError='';
const audio=$('#audio'),player=$('#player');
const fallback='data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"><rect width="300" height="300" rx="54" fill="#202023"/><path d="M75 222V78h43l32 55 32-55h43v144h-42v-75l-33 55-33-55v75z" fill="#ececef"/></svg>`);

function db(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const store=request.result.createObjectStore(STORE,{keyPath:'id'});store.createIndex('createdAt','createdAt')};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function all(){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function put(value){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction(STORE,'readwrite').objectStore(STORE).put(value);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function del(id){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction(STORE,'readwrite').objectStore(STORE).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function fileTitle(name){return name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()||'Untitled'}
function clock(seconds){if(!Number.isFinite(seconds))return'';seconds=Math.max(0,Math.floor(seconds));return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}
function duration(file){return new Promise(resolve=>{const probe=document.createElement('audio'),url=URL.createObjectURL(file);probe.preload='metadata';probe.onloadedmetadata=()=>{const value=probe.duration;URL.revokeObjectURL(url);resolve(Number.isFinite(value)?value:0)};probe.onerror=()=>{URL.revokeObjectURL(url);resolve(0)};probe.src=url})}
function text(bytes){return new TextDecoder('latin1').decode(bytes).replace(/\0+$/,'').trim()}
function synchsafe(bytes){return(bytes[0]<<21)|(bytes[1]<<14)|(bytes[2]<<7)|bytes[3]}
async function tags(file){if(!/\.mp3$/i.test(file.name))return{};try{const bytes=new Uint8Array(await file.slice(0,1024*1024).arrayBuffer());if(text(bytes.slice(0,3))!=='ID3')return{};let position=10,end=10+synchsafe(bytes.slice(6,10)),result={};while(position+10<=end&&position+10<=bytes.length){const frame=text(bytes.slice(position,position+4));if(!frame)break;const size=bytes[3]===4?synchsafe(bytes.slice(position+4,position+8)):((bytes[position+4]<<24)>>>0)|(bytes[position+5]<<16)|(bytes[position+6]<<8)|bytes[position+7];if(!size||position+10+size>bytes.length)break;const data=bytes.slice(position+10,position+10+size);if(['TIT2','TPE1','TALB'].includes(frame)){const value=text(data.slice(1));if(frame==='TIT2')result.title=value;if(frame==='TPE1')result.artist=value;if(frame==='TALB')result.album=value}if(frame==='APIC'){let index=1;while(index<data.length&&data[index])index++;const mime=text(data.slice(1,index));index+=2;while(index<data.length&&data[index])index++;index++;if(index<data.length)result.artwork=new Blob([data.slice(index)],{type:mime||'image/jpeg'})}position+=10+size}return result}catch{return{}}}
function audioSource(track){return track.audio instanceof Blob?track.audio:track.audioBlob instanceof Blob?track.audioBlob:null}
function artworkSource(track){return track.artwork instanceof Blob?track.artwork:track.artworkBlob instanceof Blob?track.artworkBlob:null}
function guessAudioType(name=''){const extension=name.toLowerCase().split('.').pop();return({mp3:'audio/mpeg',m4a:'audio/mp4',mp4:'audio/mp4',aac:'audio/aac',wav:'audio/wav',ogg:'audio/ogg',oga:'audio/ogg',opus:'audio/ogg',flac:'audio/flac'})[extension]||''}
function playableBlob(track){const source=audioSource(track);if(!source||!source.size)return null;const type=(source.type&&source.type!=='application/octet-stream')?source.type:guessAudioType(source.name||track.sourceFilename||track.filename||'');return new Blob([source],{type:type||'audio/mpeg'})}
function art(track){const artwork=artworkSource(track);if(!artwork)return fallback;const url=URL.createObjectURL(artwork);artUrls.push(url);return url}
function clearArts(){artUrls.forEach(URL.revokeObjectURL);artUrls=[]}
async function refresh(){tracks=await all();filter()}
function filter(){const query=$('#search').value.trim().toLowerCase(),sort=$('#sort').value;visible=tracks.filter(track=>!query||[track.title,track.artist,track.album].some(value=>(value||'').toLowerCase().includes(query))).sort((left,right)=>sort==='title'?left.title.localeCompare(right.title):sort==='artist'?(left.artist||'').localeCompare(right.artist||''):right.createdAt-left.createdAt);render()}
function render(){clearArts();$('#tracks').replaceChildren();$('#count').textContent=`${tracks.length} ${tracks.length===1?'song':'songs'}`;$('#empty').hidden=tracks.length>0;for(const track of visible){const row=document.createElement('li');row.className='track'+(current===track.id&&!audio.paused?' active':'');row.innerHTML=`<button class="track-main" type="button"><img class="art" alt=""><span class="track-copy"><strong></strong><span></span></span></button><span class="duration"></span><button class="icon edit" type="button" aria-label="Edit">•••</button>`;row.querySelector('.art').src=art(track);row.querySelector('strong').textContent=track.title;row.querySelector('.track-copy span').textContent=[track.artist,track.album].filter(Boolean).join(' · ')||'Unknown';row.querySelector('.duration').textContent=clock(track.duration);row.querySelector('.track-main').onclick=()=>playTrack(track.id,true);row.querySelector('.edit').onclick=()=>openEdit(track.id);$('#tracks').append(row)}}

function playbackMessage(error){if(error?.name==='NotAllowedError')return'Tap play to start.';if(error?.name==='NotSupportedError'||audio.error?.code===4)return'This audio format is not supported on this iPhone.';if(audio.error?.code===3)return'This audio file could not be decoded.';if(audio.error?.code===2)return'This audio file could not be loaded.';return'Could not play this song.'}
async function startPlayback(){try{lastPlaybackError='';await audio.play()}catch(error){console.error('Playback failed',error,audio.error);const message=playbackMessage(error);if(message!==lastPlaybackError){lastPlaybackError=message;toast(message)}updatePlayButton()}}
function updatePlayButton(){$('#play').textContent=audio.paused?'▶':'Ⅱ';$('#play').setAttribute('aria-label',audio.paused?'Play':'Pause');render()}
async function playTrack(id,shouldPlay=true){const track=tracks.find(item=>item.id===id);if(!track)return;const blob=playableBlob(track);if(!blob){toast('This song file is missing. Add it again.');return}audio.pause();audio.removeAttribute('src');audio.load();if(audioUrl)URL.revokeObjectURL(audioUrl);if(nowArtUrl)URL.revokeObjectURL(nowArtUrl);audioUrl=URL.createObjectURL(blob);audio.src=audioUrl;audio.load();current=track.id;player.hidden=false;const artwork=artworkSource(track);nowArtUrl=artwork?URL.createObjectURL(artwork):null;$('#nowArt').src=nowArtUrl||fallback;$('#nowTitle').textContent=track.title;$('#nowArtist').textContent=track.artist||'Unknown';if('mediaSession'in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:track.title,artist:track.artist||'',album:track.album||'',artwork:artwork?[{src:$('#nowArt').src,type:artwork.type||'image/jpeg'}]:[]})}render();if(shouldPlay)await startPlayback()}
function move(direction){if(!visible.length)return;let index=visible.findIndex(track=>track.id===current);if(index<0)index=0;playTrack(visible[(index+direction+visible.length)%visible.length].id,true)}

async function importFiles(event){event.preventDefault();const files=[...$('#files').files];if(!files.length)return;let done=0;for(const[index,file]of files.entries()){ $('#importStatus').textContent=`Adding ${index+1} of ${files.length}…`;try{const metadata=await tags(file);await put({id:uid(),title:metadata.title||fileTitle(file.name),artist:metadata.artist||'Unknown',album:metadata.album||'',audio:file,audioType:file.type||guessAudioType(file.name),sourceFilename:file.name,artwork:metadata.artwork||null,duration:await duration(file),createdAt:Date.now()+index});done++}catch(error){console.error(error)}}if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});$('#importDialog').close();event.target.reset();$('#importStatus').textContent='';await refresh();toast(`Added ${done} ${done===1?'song':'songs'}.`)}
function openEdit(id){const track=tracks.find(item=>item.id===id);if(!track)return;editing=track.id;pendingArt=artworkSource(track);$('#editTitle').value=track.title;$('#editArtist').value=track.artist||'';$('#editAlbum').value=track.album||'';$('#editPreview').src=pendingArt?URL.createObjectURL(pendingArt):fallback;$('#editDialog').showModal()}
async function saveEdit(event){event.preventDefault();const track=tracks.find(item=>item.id===editing);if(!track)return;const playing=current===track.id&&!audio.paused;await put({...track,audio:audioSource(track),audioBlob:undefined,title:$('#editTitle').value.trim()||track.title,artist:$('#editArtist').value.trim()||'Unknown',album:$('#editAlbum').value.trim(),artwork:pendingArt,artworkBlob:undefined});$('#editDialog').close();await refresh();if(current===track.id)playTrack(track.id,playing);toast('Saved.')}
function toast(message){const element=$('#toast');element.textContent=message;element.hidden=false;clearTimeout(element._timer);element._timer=setTimeout(()=>element.hidden=true,3000)}

['#importTop','#importHero','#importEmpty'].forEach(selector=>$(selector).onclick=()=>$('#importDialog').showModal());
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());
$('#importForm').onsubmit=importFiles;$('#editForm').onsubmit=saveEdit;$('#search').oninput=filter;$('#sort').onchange=filter;
$('#play').onclick=()=>{if(!current&&visible.length){playTrack(visible[0].id,true);return}audio.paused?startPlayback():audio.pause()};$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);
audio.onplay=updatePlayButton;audio.onpause=updatePlayButton;audio.onended=()=>move(1);audio.onerror=()=>{const message=playbackMessage();if(message!==lastPlaybackError){lastPlaybackError=message;toast(message)}updatePlayButton()};
$('#editArt').onchange=event=>{const file=event.target.files[0];if(file){pendingArt=file;$('#editPreview').src=URL.createObjectURL(file)}};
$('#delete').onclick=async()=>{if(!editing||!confirm('Delete this song?'))return;const wasCurrent=current===editing;await del(editing);$('#editDialog').close();if(wasCurrent){audio.pause();audio.removeAttribute('src');audio.load();current=null;player.hidden=true}await refresh();toast('Deleted.')};
if('mediaSession'in navigator){for(const[action,handler]of Object.entries({play:startPlayback,pause:()=>audio.pause(),previoustrack:()=>move(-1),nexttrack:()=>move(1)}))try{navigator.mediaSession.setActionHandler(action,handler)}catch{}}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
refresh().catch(error=>{console.error(error);toast('Library unavailable.')});
